### ISSUE TITLE
RandomForestRegressor

### ISSUE THREAD

**Issue by jessie831024** [emlearn/emlearn#31]
Can you add feature support for RandomForestRegressor?

**Comment by jonnor** [comment]
Hi! Thank for the request. A couple of others have asked for the same. Also related is #14.

In the coming weeks I do not think that I will have time to implement this, unfortunately. Contributions are very welcomed!

**Comment by jonnor** [comment]
Stumbled over this very simple implementation, https://data-and-the-world.onrender.com/posts/python-random-forest-c/

**Comment by kkmoslehpour** [comment]
Also looking for support for RandomForestRegressor

**Comment by jonnor** [comment]
Implemented now in https://github.com/emlearn/emlearn/pull/54

**Comment by jonnor** [comment]
This feature was released in emlearn 0.16.3 on 01.01.2023: https://github.com/emlearn/emlearn/releases/tag/0.16.3
